<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>inspection_bringup</name>
  <version>0.1.0</version>
  <description>Top-level launch files to bring up the full inspection stack.</description>
  <maintainer email="3250168367@qq.com">soul0109</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>robot_description</exec_depend>
  <exec_depend>simulation_worlds</exec_depend>
  <exec_depend>vision_perception</exec_depend>
  <exec_depend>inspection_mission</exec_depend>
  <exec_depend>navigation_config</exec_depend>
  <exec_depend>inspection_interfaces</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
